name = "hugo-theme-next"
license = "MIT"
licenselink = "https://github.com/pplmx/hugo-theme-next/blob/main/LICENSE"
description = "A personal blog site theme."
homepage = "https://yoooo.fun"
tags = ["Blog", "Simple", "Dark", "Personal", "Fast", "Theme"]
features = ["some", "awesome", "features"]
min_version = "0.59.1"

[author]
name = "Mystic"
homepage = "https://yoooo.fun"

[original]
author = "elkan"
homepage = "https://lisenhui.cn"
repo = "https://github.com/elkan1788/hugo-theme-next.git"
